### ISSUE TITLE
Current karma count

### ISSUE THREAD

**Issue by jwilson-slalom** [jwilson-slalom/xBot#37]

**Comment by jwilson-slalom** [comment]
Thoughts on a MVP implementation? 

Was thinking of keeping it simple by just doing a slash command of `/karma {User}, {User}, ... ` 

We could also do it as a message that xBot parses? Seems easiest to just do the slash command and keep it simple @ichibod @allenhumphreys

**Comment by allenhumphreys** [comment]
Slash command seems good and the most user friendly as it is not a guessing game with the format

**Comment by allenhumphreys** [comment]
I would like to follow that up with we haven't seen the slash commands fully functional yet, so we might want to decide as the work goes on.
