### ISSUE TITLE
/karma will conflict with the existing karma bot

### ISSUE THREAD

**Issue by allenhumphreys** [jwilson-slalom/xBot#58]
I'm not sure IT is going to be keeping that bot, but since slash commands are global they need to be unique. Personally I'd rather not use slash commands at all in favor of `@botname leaderboard` or `@botname status @jacob`. Either way, if we go forward with slash commands, we'll need to resolve that conflict I think before we request to be added to the workspace.

**Comment by jwilson-slalom** [comment]
I think the nice feature of the slash commands is that they are automatically ephemeral by nature. But. If someone wanted to just privately use leaderboard / karma then they could just message the bot directly. I think I could go either way on their existence

**Comment by jwilson-slalom** [comment]
As I have been thinking about this more, I am leaning more on the idea of disabling the / commands and transitioning all interactions to take place with messages.
